use_frameworks!

target 'QuickShotUtils_Example' do
  pod 'QuickShotUtils', :path => '../'

  target 'QuickShotUtils_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
